embeddings:
  batch_size: 32
  cache_enabled: true
  dimension: 768
  model: nomic-ai/nomic-embed-text-v1
  provider: nomic_local
  task_type: search_document
evaluation:
  metrics:
  - name: rouge
    parameters:
      rouge_types:
      - rouge1
      - rouge2
      - rougeL
  - name: semantic_similarity
    parameters:
      model: nomic-embed-text-v1.5
  - name: response_time
  - name: token_count
llm_providers:
  ollama:
    models:
    - name: llama3
      parameters:
        max_tokens: 512
        temperature: 0.7
    - name: mistral
      parameters:
        max_tokens: 512
        temperature: 0.7
    - name: phi3
      parameters:
        max_tokens: 512
        temperature: 0.7
  openai:
    models:
    - name: gpt-3.5-turbo
      parameters:
        max_tokens: 512
        temperature: 0.7
    - name: gpt-4
      parameters:
        max_tokens: 512
        temperature: 0.7
rag:
  chunk_overlap: 128
  chunk_size: 512
  similarity_top_k: 5
ui:
  default_page: Home
  max_display_items: 50
  refresh_interval: 5
  theme: light
web_crawling:
  max_depth: 3
  max_pages: 100
  respect_robots_txt: true
  timeout: 30
  user_agent: LLM-Comparison-Tool/0.1.0
