name: llm-comparison
version: '3.8'

services:
  # Choose ONE of these database options by uncommenting

  # Option 1: Local PostgreSQL Vector Database
  vectordb:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-llm_comparison}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - vectordb_data:/var/lib/postgresql/data
    restart: unless-stopped
    
  # Web application
  webapp:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - vectordb
    environment:
      # Database connection (use these for local vectordb)
      - DB_PROVIDER=${DB_PROVIDER:-postgres}
      - POSTGRES_HOST=${POSTGRES_HOST:-vectordb}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-llm_comparison}
      
      # Supabase connection (use these if DB_PROVIDER=supabase)
      - SUPABASE_URL=${SUPABASE_URL:-}
      - SUPABASE_KEY=${SUPABASE_KEY:-}
      - SUPABASE_TABLE=${SUPABASE_TABLE:-embeddings}
      
      # External Opik connection
      - OPIK_HOST=${OPIK_HOST:-localhost}
      - OPIK_PORT=${OPIK_BACKEND_PORT:-8000}
    restart: unless-stopped

volumes:
  vectordb_data:
